const data = {
  products: [
    {
      name: 'Akademia Sztuk Pięknych',
      author: 'Avi x Louis Villain',
      slug: 'Akademia_Sztuk_Pięknych',
      category: 'Rap',
      image: '/images/p1.jpg', //350px x 350px
      price: 49,
      countInStock: 70,
      musicLabel: 'Moya Label',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality music',
    },
    {
      name: 'Zbiór Pieśni Sycylijskich',
      author: 'Avi x Louis Villain',
      slug: 'Zbiór_Pieśni_Sycylijskich',
      category: 'Rap',
      image: '/images/p2.jpg',
      price: 80,
      countInStock: 100,
      musicLabel: 'Moya Label',
      rating: 4,
      numReviews: 23,
      description: 'High quality music',
    },
    {
      name: 'Native',
      author: 'OneRepublic',
      slug: 'Native',
      category: 'Pop',
      image: '/images/p3.jpg',
      price: 20,
      countInStock: 100,
      musicLabel: 'Universal Music',
      rating: 3,
      numReviews: 40,
      description: 'High quality music',
    },
    {
      name: 'Music Of The Spheres',
      author: 'Coldplay',
      slug: 'Music_Of_The_Spheres',
      category: 'Pop',
      image: '/images/p4.jpg',
      price: 39,
      countInStock: 170,
      musicLabel: 'Warner Music',
      rating: 2,
      numReviews: 7,
      description: 'High quality music',
    },
  ],
};
export default data;
